# Generated by Django 4.1.3 on 2022-11-13 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('a_id', models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='Patente')),
                ('a_brand', models.CharField(max_length=50, verbose_name='Marca')),
                ('a_model', models.CharField(max_length=50, verbose_name='Modelo')),
                ('a_color', models.CharField(max_length=15, verbose_name='Color')),
                ('a_state', models.CharField(max_length=15, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Auto',
                'verbose_name_plural': 'Autos',
                'ordering': ['a_brand', 'a_model'],
            },
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('c_email', models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='c_email')),
                ('c_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('c_lastname', models.CharField(max_length=50, verbose_name='Apellido')),
                ('c_pnumber', models.CharField(max_length=15, verbose_name='Telefono')),
                ('c_image', models.URLField(max_length=254, verbose_name='Imagen')),
                ('c_state', models.CharField(max_length=15, verbose_name='Estado')),
                ('c_car', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_car', to='movilAPI.auto')),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
                'ordering': ['c_lastname', 'c_name'],
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('v_viaje_id', models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='Identificador viaje')),
                ('v_com_dest', models.CharField(max_length=15, verbose_name='Comuna destino')),
                ('v_dir_dest', models.CharField(max_length=15, verbose_name='Direccion destino')),
                ('v_val_trip', models.IntegerField(verbose_name='Valor viaje')),
                ('v_state', models.CharField(max_length=15, verbose_name='Estado')),
                ('v_auto_id', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='ID_Auto', to='movilAPI.conductor')),
                ('v_conductor_id', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='ID_conductor', to='movilAPI.conductor')),
                ('v_pasajero_id', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='ID_Pasajero', to='movilAPI.conductor')),
            ],
            options={
                'verbose_name': 'Viaje',
                'verbose_name_plural': 'Viajes',
                'ordering': ['v_viaje_id', 'v_conductor_id', 'v_pasajero_id'],
            },
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('p_email', models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='p_email')),
                ('p_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('p_lastname', models.CharField(max_length=50, verbose_name='Apellido')),
                ('p_pnumber', models.CharField(max_length=15, verbose_name='Telefono')),
                ('p_image', models.URLField(max_length=254, verbose_name='Imagen')),
                ('p_state', models.CharField(max_length=10, verbose_name='Estado')),
                ('p_trip', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_trip', to='movilAPI.viaje')),
            ],
            options={
                'verbose_name': 'Pasajero',
                'verbose_name_plural': 'Pasajeros',
                'ordering': ['p_lastname', 'p_name'],
            },
        ),
        migrations.AddField(
            model_name='conductor',
            name='c_trip',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_trip', to='movilAPI.viaje'),
        ),
        migrations.AddField(
            model_name='auto',
            name='a_conductor',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='a_conductor', to='movilAPI.conductor'),
        ),
    ]
