# Generated by Django 4.1.3 on 2022-11-13 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movilAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='a_conductor',
        ),
    ]
