# Generated by Django 4.1.3 on 2022-11-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movilAPI', '0002_remove_auto_a_conductor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductor',
            name='c_trip',
        ),
        migrations.RemoveField(
            model_name='pasajero',
            name='p_trip',
        ),
        migrations.AlterField(
            model_name='auto',
            name='a_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Patente'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='v_viaje_id',
            field=models.CharField(max_length=254, primary_key=True, serialize=False, verbose_name='Identificador de viaje'),
        ),
    ]
