# Generated by Django 4.1.3 on 2022-11-13 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movilAPI', '0003_remove_conductor_c_trip_remove_pasajero_p_trip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='c_email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='pasajero',
            name='p_email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='v_auto_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='ID_Auto', to='movilAPI.auto'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='v_pasajero_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='ID_Pasajero', to='movilAPI.pasajero'),
        ),
    ]
