# Generated by Django 4.1.3 on 2022-11-13 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movilAPI', '0005_alter_viaje_v_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='v_com_dest',
            field=models.CharField(max_length=30, verbose_name='Comuna destino'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='v_dir_dest',
            field=models.CharField(max_length=30, verbose_name='Direccion destino'),
        ),
    ]
