# Generated by Django 4.1.3 on 2022-11-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movilAPI', '0006_alter_viaje_v_com_dest_alter_viaje_v_dir_dest'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='c_password',
            field=models.CharField(default='Password123', max_length=32, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='pasajero',
            name='p_password',
            field=models.CharField(default='Password123', max_length=32, verbose_name='Password'),
        ),
    ]
