# Generated by Django 4.1.3 on 2022-11-16 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movilAPI', '0010_alter_viaje_v_auto_id_alter_viaje_v_conductor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='c_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_car', to='movilAPI.auto'),
        ),
    ]
