# Generated by Django 4.1.3 on 2022-11-16 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movilAPI', '0011_alter_conductor_c_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='a_conductor',
        ),
    ]
