# Generated by Django 4.1.3 on 2022-11-16 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movilAPI', '0012_remove_auto_a_conductor'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='a_conductor',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, related_name='a_conductor', to='movilAPI.conductor'),
        ),
    ]
