# Generated by Django 4.1.3 on 2022-11-16 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movilAPI', '0015_conductor_c_trip_pasajero_p_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasajero',
            name='p_trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_trip', to='movilAPI.viaje'),
        ),
    ]
