# Generated by Django 4.1.3 on 2022-11-16 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movilAPI', '0019_remove_auto_a_conductor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductor',
            name='c_trip',
        ),
    ]
