# Generated by Django 4.1.3 on 2022-11-16 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movilAPI', '0020_remove_conductor_c_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasajero',
            name='p_trip',
        ),
    ]
