# Generated by Django 4.1.3 on 2022-11-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movilAPI', '0021_remove_pasajero_p_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasajero',
            name='p_state',
            field=models.CharField(default='offline', max_length=10, verbose_name='Estado'),
        ),
    ]
