# Generated by Django 4.1.3 on 2022-11-17 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movilAPI', '0023_alter_viaje_v_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='c_car',
            field=models.ForeignKey(blank='True', on_delete=django.db.models.deletion.CASCADE, related_name='c_car', to='movilAPI.auto'),
        ),
    ]
