# Generated by Django 4.1.3 on 2022-11-17 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movilAPI', '0025_alter_conductor_c_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='a_conductor',
            field=models.ForeignKey(default='Sin conductor', on_delete=django.db.models.deletion.CASCADE, related_name='a_conductor', to='movilAPI.conductor'),
        ),
    ]
