# Generated by Django 4.1.3 on 2022-11-17 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movilAPI', '0028_alter_viaje_v_viaje_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='a_conductor',
        ),
        migrations.AlterField(
            model_name='conductor',
            name='c_car',
            field=models.ForeignKey(default='Sin auto', on_delete=django.db.models.deletion.CASCADE, related_name='c_car', to='movilAPI.auto'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='v_viaje_id',
            field=models.CharField(max_length=254, primary_key=True, serialize=False, verbose_name='Identificador de viaje'),
        ),
    ]
