# Generated by Django 4.1.3 on 2022-11-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movilAPI', '0029_remove_auto_a_conductor_alter_conductor_c_car_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='c_image',
            field=models.URLField(default='https://ionicframework.com/docs/img/demos/avatar.svg', max_length=254, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='c_lastname',
            field=models.CharField(blank=True, max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='c_pnumber',
            field=models.CharField(blank=True, max_length=15, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='c_state',
            field=models.CharField(default='Desconectado', max_length=15, verbose_name='Estado'),
        ),
    ]
