# Generated by Django 4.1.3 on 2022-11-19 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movilAPI', '0030_alter_conductor_c_image_alter_conductor_c_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasajero',
            name='p_image',
            field=models.URLField(default='https://ionicframework.com/docs/img/demos/avatar.svg', max_length=254, verbose_name='Imagen'),
        ),
    ]
