# Generated by Django 4.1.3 on 2022-12-11 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movilAPI', '0031_alter_pasajero_p_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='v_viaje_id',
            field=models.AutoField(max_length=254, primary_key=True, serialize=False, verbose_name='Identificador de viaje'),
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False, verbose_name='ID_solicitud')),
                ('precio_oferta', models.IntegerField(verbose_name='Valor')),
                ('p_comuna_destino', models.CharField(max_length=30, verbose_name='Comuna destino')),
                ('p_direccion_destino', models.CharField(max_length=30, verbose_name='Dirección de destino')),
                ('pk_pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PK_Conductor_Solicitud', to='movilAPI.pasajero')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'ordering': ['id_solicitud', 'pk_pasajero'],
            },
        ),
    ]
