# Generated by Django 4.1.3 on 2022-12-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movilAPI', '0032_alter_viaje_v_viaje_id_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='v_viaje_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador de viaje'),
        ),
    ]
