# Generated by Django 4.1.3 on 2022-12-11 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movilAPI', '0033_alter_viaje_v_viaje_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitud',
            options={'ordering': ['id_solicitud', 'p_email'], 'verbose_name': 'Solicitud', 'verbose_name_plural': 'Solicitudes'},
        ),
        migrations.RenameField(
            model_name='solicitud',
            old_name='pk_pasajero',
            new_name='p_email',
        ),
    ]
