# Generated by Django 4.1.3 on 2022-12-11 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movilAPI', '0034_alter_solicitud_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='precio_oferta',
            field=models.IntegerField(default=0, verbose_name='Valor'),
        ),
    ]
