# Generated by Django 4.1.3 on 2022-12-11 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movilAPI', '0035_alter_solicitud_precio_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='p_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Nombre pasajero'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='p_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PK_pasajero_Solicitud', to='movilAPI.pasajero'),
        ),
    ]
