# Generated by Django 4.1.3 on 2022-12-12 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movilAPI', '0036_solicitud_p_name_alter_solicitud_p_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitud',
            options={'ordering': ['p_email'], 'verbose_name': 'Solicitud', 'verbose_name_plural': 'Solicitudes'},
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='id_solicitud',
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='p_email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='Email_pasajero'),
        ),
    ]
